__title__ = "PyBypass"
__description__ = "Python module for bypassing different kind of links."
__version__ = "2.0.1"
__author__ = "zeynDev"
__author_email__ = "-"
__license__ = "MIT"
__copyright__ = "Copyright 2050 @ ZeynDev"
